/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThreeDimensionIndexImport } from './routes/three-dimension/index'
import { Route as AudioIndexImport } from './routes/audio/index'
import { Route as AudioSpeechImport } from './routes/audio/speech'
import { Route as AudioMicImport } from './routes/audio/mic'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreeDimensionIndexRoute = ThreeDimensionIndexImport.update({
  id: '/three-dimension/',
  path: '/three-dimension/',
  getParentRoute: () => rootRoute,
} as any)

const AudioIndexRoute = AudioIndexImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRoute,
} as any)

const AudioSpeechRoute = AudioSpeechImport.update({
  id: '/audio/speech',
  path: '/audio/speech',
  getParentRoute: () => rootRoute,
} as any)

const AudioMicRoute = AudioMicImport.update({
  id: '/audio/mic',
  path: '/audio/mic',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/audio/mic': {
      id: '/audio/mic'
      path: '/audio/mic'
      fullPath: '/audio/mic'
      preLoaderRoute: typeof AudioMicImport
      parentRoute: typeof rootRoute
    }
    '/audio/speech': {
      id: '/audio/speech'
      path: '/audio/speech'
      fullPath: '/audio/speech'
      preLoaderRoute: typeof AudioSpeechImport
      parentRoute: typeof rootRoute
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioIndexImport
      parentRoute: typeof rootRoute
    }
    '/three-dimension/': {
      id: '/three-dimension/'
      path: '/three-dimension'
      fullPath: '/three-dimension'
      preLoaderRoute: typeof ThreeDimensionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/audio': typeof AudioIndexRoute
  '/three-dimension': typeof ThreeDimensionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/audio': typeof AudioIndexRoute
  '/three-dimension': typeof ThreeDimensionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/audio/': typeof AudioIndexRoute
  '/three-dimension/': typeof ThreeDimensionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio/mic'
    | '/audio/speech'
    | '/audio'
    | '/three-dimension'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio/mic' | '/audio/speech' | '/audio' | '/three-dimension'
  id:
    | '__root__'
    | '/'
    | '/audio/mic'
    | '/audio/speech'
    | '/audio/'
    | '/three-dimension/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioMicRoute: typeof AudioMicRoute
  AudioSpeechRoute: typeof AudioSpeechRoute
  AudioIndexRoute: typeof AudioIndexRoute
  ThreeDimensionIndexRoute: typeof ThreeDimensionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioMicRoute: AudioMicRoute,
  AudioSpeechRoute: AudioSpeechRoute,
  AudioIndexRoute: AudioIndexRoute,
  ThreeDimensionIndexRoute: ThreeDimensionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/audio/mic",
        "/audio/speech",
        "/audio/",
        "/three-dimension/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/audio/mic": {
      "filePath": "audio/mic.tsx"
    },
    "/audio/speech": {
      "filePath": "audio/speech.tsx"
    },
    "/audio/": {
      "filePath": "audio/index.tsx"
    },
    "/three-dimension/": {
      "filePath": "three-dimension/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
