/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as StableFluidsRouteImport } from './routes/stable-fluids'
import { Route as ShaderRouteImport } from './routes/shader'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MeltTheBorderRouteImport } from './routes/melt-the-border'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIndexRouteImport } from './routes/trade/index'
import { Route as ThreeDimensionIndexRouteImport } from './routes/three-dimension/index'
import { Route as NoiseIndexRouteImport } from './routes/noise/index'
import { Route as AudioIndexRouteImport } from './routes/audio/index'
import { Route as AggregateBillIndexRouteImport } from './routes/aggregate-bill/index'
import { Route as TradeTokenRouteImport } from './routes/trade/$token'
import { Route as ThreeDimensionShadowsRouteImport } from './routes/three-dimension/shadows'
import { Route as ThreeDimensionShaderRouteImport } from './routes/three-dimension/shader'
import { Route as ThreeDimensionParticleRouteImport } from './routes/three-dimension/particle'
import { Route as SamplesSquareAparkRouteImport } from './routes/samples/square-apark'
import { Route as SamplesNormalCircleRouteImport } from './routes/samples/normal-circle'
import { Route as SamplesFollowerCircleRouteImport } from './routes/samples/follower-circle'
import { Route as SamplesAudioCircleRouteImport } from './routes/samples/audio-circle'
import { Route as Samples5starParticleRouteImport } from './routes/samples/5star-particle'
import { Route as NoiseFractalRouteImport } from './routes/noise/fractal'
import { Route as NoiseFbmRouteImport } from './routes/noise/fbm'
import { Route as NoiseCellularRouteImport } from './routes/noise/cellular'
import { Route as DetectionPoseRouteImport } from './routes/detection/pose'
import { Route as DetectionHandPoseRouteImport } from './routes/detection/hand-pose'
import { Route as DetectionFluidRouteImport } from './routes/detection/fluid'
import { Route as DetectionFaceLandmarkRouteImport } from './routes/detection/face-landmark'
import { Route as DetectionDetectorRouteImport } from './routes/detection/detector'
import { Route as AudioSpeechRouteImport } from './routes/audio/speech'
import { Route as AudioMicRouteImport } from './routes/audio/mic'
import { Route as AggregateBillSummaryRouteImport } from './routes/aggregate-bill/summary'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const StableFluidsRoute = StableFluidsRouteImport.update({
  id: '/stable-fluids',
  path: '/stable-fluids',
  getParentRoute: () => rootRouteImport,
} as any)
const ShaderRoute = ShaderRouteImport.update({
  id: '/shader',
  path: '/shader',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MeltTheBorderRoute = MeltTheBorderRouteImport.update({
  id: '/melt-the-border',
  path: '/melt-the-border',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIndexRoute = TradeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradeRoute,
} as any)
const ThreeDimensionIndexRoute = ThreeDimensionIndexRouteImport.update({
  id: '/three-dimension/',
  path: '/three-dimension/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiseIndexRoute = NoiseIndexRouteImport.update({
  id: '/noise/',
  path: '/noise/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIndexRoute = AudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregateBillIndexRoute = AggregateBillIndexRouteImport.update({
  id: '/aggregate-bill/',
  path: '/aggregate-bill/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTokenRoute = TradeTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => TradeRoute,
} as any)
const ThreeDimensionShadowsRoute = ThreeDimensionShadowsRouteImport.update({
  id: '/three-dimension/shadows',
  path: '/three-dimension/shadows',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreeDimensionShaderRoute = ThreeDimensionShaderRouteImport.update({
  id: '/three-dimension/shader',
  path: '/three-dimension/shader',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreeDimensionParticleRoute = ThreeDimensionParticleRouteImport.update({
  id: '/three-dimension/particle',
  path: '/three-dimension/particle',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSquareAparkRoute = SamplesSquareAparkRouteImport.update({
  id: '/samples/square-apark',
  path: '/samples/square-apark',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesNormalCircleRoute = SamplesNormalCircleRouteImport.update({
  id: '/samples/normal-circle',
  path: '/samples/normal-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesFollowerCircleRoute = SamplesFollowerCircleRouteImport.update({
  id: '/samples/follower-circle',
  path: '/samples/follower-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesAudioCircleRoute = SamplesAudioCircleRouteImport.update({
  id: '/samples/audio-circle',
  path: '/samples/audio-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const Samples5starParticleRoute = Samples5starParticleRouteImport.update({
  id: '/samples/5star-particle',
  path: '/samples/5star-particle',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiseFractalRoute = NoiseFractalRouteImport.update({
  id: '/noise/fractal',
  path: '/noise/fractal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiseFbmRoute = NoiseFbmRouteImport.update({
  id: '/noise/fbm',
  path: '/noise/fbm',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiseCellularRoute = NoiseCellularRouteImport.update({
  id: '/noise/cellular',
  path: '/noise/cellular',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionPoseRoute = DetectionPoseRouteImport.update({
  id: '/detection/pose',
  path: '/detection/pose',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionHandPoseRoute = DetectionHandPoseRouteImport.update({
  id: '/detection/hand-pose',
  path: '/detection/hand-pose',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionFluidRoute = DetectionFluidRouteImport.update({
  id: '/detection/fluid',
  path: '/detection/fluid',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionFaceLandmarkRoute = DetectionFaceLandmarkRouteImport.update({
  id: '/detection/face-landmark',
  path: '/detection/face-landmark',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionDetectorRoute = DetectionDetectorRouteImport.update({
  id: '/detection/detector',
  path: '/detection/detector',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioSpeechRoute = AudioSpeechRouteImport.update({
  id: '/audio/speech',
  path: '/audio/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioMicRoute = AudioMicRouteImport.update({
  id: '/audio/mic',
  path: '/audio/mic',
  getParentRoute: () => rootRouteImport,
} as any)
const AggregateBillSummaryRoute = AggregateBillSummaryRouteImport.update({
  id: '/aggregate-bill/summary',
  path: '/aggregate-bill/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/melt-the-border': typeof MeltTheBorderRoute
  '/playground': typeof PlaygroundRoute
  '/shader': typeof ShaderRoute
  '/stable-fluids': typeof StableFluidsRoute
  '/trade': typeof TradeRouteWithChildren
  '/aggregate-bill/summary': typeof AggregateBillSummaryRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/detection/detector': typeof DetectionDetectorRoute
  '/detection/face-landmark': typeof DetectionFaceLandmarkRoute
  '/detection/fluid': typeof DetectionFluidRoute
  '/detection/hand-pose': typeof DetectionHandPoseRoute
  '/detection/pose': typeof DetectionPoseRoute
  '/noise/cellular': typeof NoiseCellularRoute
  '/noise/fbm': typeof NoiseFbmRoute
  '/noise/fractal': typeof NoiseFractalRoute
  '/samples/5star-particle': typeof Samples5starParticleRoute
  '/samples/audio-circle': typeof SamplesAudioCircleRoute
  '/samples/follower-circle': typeof SamplesFollowerCircleRoute
  '/samples/normal-circle': typeof SamplesNormalCircleRoute
  '/samples/square-apark': typeof SamplesSquareAparkRoute
  '/three-dimension/particle': typeof ThreeDimensionParticleRoute
  '/three-dimension/shader': typeof ThreeDimensionShaderRoute
  '/three-dimension/shadows': typeof ThreeDimensionShadowsRoute
  '/trade/$token': typeof TradeTokenRoute
  '/aggregate-bill/': typeof AggregateBillIndexRoute
  '/audio/': typeof AudioIndexRoute
  '/noise/': typeof NoiseIndexRoute
  '/three-dimension/': typeof ThreeDimensionIndexRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/melt-the-border': typeof MeltTheBorderRoute
  '/playground': typeof PlaygroundRoute
  '/shader': typeof ShaderRoute
  '/stable-fluids': typeof StableFluidsRoute
  '/aggregate-bill/summary': typeof AggregateBillSummaryRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/detection/detector': typeof DetectionDetectorRoute
  '/detection/face-landmark': typeof DetectionFaceLandmarkRoute
  '/detection/fluid': typeof DetectionFluidRoute
  '/detection/hand-pose': typeof DetectionHandPoseRoute
  '/detection/pose': typeof DetectionPoseRoute
  '/noise/cellular': typeof NoiseCellularRoute
  '/noise/fbm': typeof NoiseFbmRoute
  '/noise/fractal': typeof NoiseFractalRoute
  '/samples/5star-particle': typeof Samples5starParticleRoute
  '/samples/audio-circle': typeof SamplesAudioCircleRoute
  '/samples/follower-circle': typeof SamplesFollowerCircleRoute
  '/samples/normal-circle': typeof SamplesNormalCircleRoute
  '/samples/square-apark': typeof SamplesSquareAparkRoute
  '/three-dimension/particle': typeof ThreeDimensionParticleRoute
  '/three-dimension/shader': typeof ThreeDimensionShaderRoute
  '/three-dimension/shadows': typeof ThreeDimensionShadowsRoute
  '/trade/$token': typeof TradeTokenRoute
  '/aggregate-bill': typeof AggregateBillIndexRoute
  '/audio': typeof AudioIndexRoute
  '/noise': typeof NoiseIndexRoute
  '/three-dimension': typeof ThreeDimensionIndexRoute
  '/trade': typeof TradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/melt-the-border': typeof MeltTheBorderRoute
  '/playground': typeof PlaygroundRoute
  '/shader': typeof ShaderRoute
  '/stable-fluids': typeof StableFluidsRoute
  '/trade': typeof TradeRouteWithChildren
  '/aggregate-bill/summary': typeof AggregateBillSummaryRoute
  '/audio/mic': typeof AudioMicRoute
  '/audio/speech': typeof AudioSpeechRoute
  '/detection/detector': typeof DetectionDetectorRoute
  '/detection/face-landmark': typeof DetectionFaceLandmarkRoute
  '/detection/fluid': typeof DetectionFluidRoute
  '/detection/hand-pose': typeof DetectionHandPoseRoute
  '/detection/pose': typeof DetectionPoseRoute
  '/noise/cellular': typeof NoiseCellularRoute
  '/noise/fbm': typeof NoiseFbmRoute
  '/noise/fractal': typeof NoiseFractalRoute
  '/samples/5star-particle': typeof Samples5starParticleRoute
  '/samples/audio-circle': typeof SamplesAudioCircleRoute
  '/samples/follower-circle': typeof SamplesFollowerCircleRoute
  '/samples/normal-circle': typeof SamplesNormalCircleRoute
  '/samples/square-apark': typeof SamplesSquareAparkRoute
  '/three-dimension/particle': typeof ThreeDimensionParticleRoute
  '/three-dimension/shader': typeof ThreeDimensionShaderRoute
  '/three-dimension/shadows': typeof ThreeDimensionShadowsRoute
  '/trade/$token': typeof TradeTokenRoute
  '/aggregate-bill/': typeof AggregateBillIndexRoute
  '/audio/': typeof AudioIndexRoute
  '/noise/': typeof NoiseIndexRoute
  '/three-dimension/': typeof ThreeDimensionIndexRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/melt-the-border'
    | '/playground'
    | '/shader'
    | '/stable-fluids'
    | '/trade'
    | '/aggregate-bill/summary'
    | '/audio/mic'
    | '/audio/speech'
    | '/detection/detector'
    | '/detection/face-landmark'
    | '/detection/fluid'
    | '/detection/hand-pose'
    | '/detection/pose'
    | '/noise/cellular'
    | '/noise/fbm'
    | '/noise/fractal'
    | '/samples/5star-particle'
    | '/samples/audio-circle'
    | '/samples/follower-circle'
    | '/samples/normal-circle'
    | '/samples/square-apark'
    | '/three-dimension/particle'
    | '/three-dimension/shader'
    | '/three-dimension/shadows'
    | '/trade/$token'
    | '/aggregate-bill/'
    | '/audio/'
    | '/noise/'
    | '/three-dimension/'
    | '/trade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/melt-the-border'
    | '/playground'
    | '/shader'
    | '/stable-fluids'
    | '/aggregate-bill/summary'
    | '/audio/mic'
    | '/audio/speech'
    | '/detection/detector'
    | '/detection/face-landmark'
    | '/detection/fluid'
    | '/detection/hand-pose'
    | '/detection/pose'
    | '/noise/cellular'
    | '/noise/fbm'
    | '/noise/fractal'
    | '/samples/5star-particle'
    | '/samples/audio-circle'
    | '/samples/follower-circle'
    | '/samples/normal-circle'
    | '/samples/square-apark'
    | '/three-dimension/particle'
    | '/three-dimension/shader'
    | '/three-dimension/shadows'
    | '/trade/$token'
    | '/aggregate-bill'
    | '/audio'
    | '/noise'
    | '/three-dimension'
    | '/trade'
  id:
    | '__root__'
    | '/'
    | '/melt-the-border'
    | '/playground'
    | '/shader'
    | '/stable-fluids'
    | '/trade'
    | '/aggregate-bill/summary'
    | '/audio/mic'
    | '/audio/speech'
    | '/detection/detector'
    | '/detection/face-landmark'
    | '/detection/fluid'
    | '/detection/hand-pose'
    | '/detection/pose'
    | '/noise/cellular'
    | '/noise/fbm'
    | '/noise/fractal'
    | '/samples/5star-particle'
    | '/samples/audio-circle'
    | '/samples/follower-circle'
    | '/samples/normal-circle'
    | '/samples/square-apark'
    | '/three-dimension/particle'
    | '/three-dimension/shader'
    | '/three-dimension/shadows'
    | '/trade/$token'
    | '/aggregate-bill/'
    | '/audio/'
    | '/noise/'
    | '/three-dimension/'
    | '/trade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeltTheBorderRoute: typeof MeltTheBorderRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ShaderRoute: typeof ShaderRoute
  StableFluidsRoute: typeof StableFluidsRoute
  TradeRoute: typeof TradeRouteWithChildren
  AggregateBillSummaryRoute: typeof AggregateBillSummaryRoute
  AudioMicRoute: typeof AudioMicRoute
  AudioSpeechRoute: typeof AudioSpeechRoute
  DetectionDetectorRoute: typeof DetectionDetectorRoute
  DetectionFaceLandmarkRoute: typeof DetectionFaceLandmarkRoute
  DetectionFluidRoute: typeof DetectionFluidRoute
  DetectionHandPoseRoute: typeof DetectionHandPoseRoute
  DetectionPoseRoute: typeof DetectionPoseRoute
  NoiseCellularRoute: typeof NoiseCellularRoute
  NoiseFbmRoute: typeof NoiseFbmRoute
  NoiseFractalRoute: typeof NoiseFractalRoute
  Samples5starParticleRoute: typeof Samples5starParticleRoute
  SamplesAudioCircleRoute: typeof SamplesAudioCircleRoute
  SamplesFollowerCircleRoute: typeof SamplesFollowerCircleRoute
  SamplesNormalCircleRoute: typeof SamplesNormalCircleRoute
  SamplesSquareAparkRoute: typeof SamplesSquareAparkRoute
  ThreeDimensionParticleRoute: typeof ThreeDimensionParticleRoute
  ThreeDimensionShaderRoute: typeof ThreeDimensionShaderRoute
  ThreeDimensionShadowsRoute: typeof ThreeDimensionShadowsRoute
  AggregateBillIndexRoute: typeof AggregateBillIndexRoute
  AudioIndexRoute: typeof AudioIndexRoute
  NoiseIndexRoute: typeof NoiseIndexRoute
  ThreeDimensionIndexRoute: typeof ThreeDimensionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable-fluids': {
      id: '/stable-fluids'
      path: '/stable-fluids'
      fullPath: '/stable-fluids'
      preLoaderRoute: typeof StableFluidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shader': {
      id: '/shader'
      path: '/shader'
      fullPath: '/shader'
      preLoaderRoute: typeof ShaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melt-the-border': {
      id: '/melt-the-border'
      path: '/melt-the-border'
      fullPath: '/melt-the-border'
      preLoaderRoute: typeof MeltTheBorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/': {
      id: '/trade/'
      path: '/'
      fullPath: '/trade/'
      preLoaderRoute: typeof TradeIndexRouteImport
      parentRoute: typeof TradeRoute
    }
    '/three-dimension/': {
      id: '/three-dimension/'
      path: '/three-dimension'
      fullPath: '/three-dimension/'
      preLoaderRoute: typeof ThreeDimensionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noise/': {
      id: '/noise/'
      path: '/noise'
      fullPath: '/noise/'
      preLoaderRoute: typeof NoiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof AudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregate-bill/': {
      id: '/aggregate-bill/'
      path: '/aggregate-bill'
      fullPath: '/aggregate-bill/'
      preLoaderRoute: typeof AggregateBillIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$token': {
      id: '/trade/$token'
      path: '/$token'
      fullPath: '/trade/$token'
      preLoaderRoute: typeof TradeTokenRouteImport
      parentRoute: typeof TradeRoute
    }
    '/three-dimension/shadows': {
      id: '/three-dimension/shadows'
      path: '/three-dimension/shadows'
      fullPath: '/three-dimension/shadows'
      preLoaderRoute: typeof ThreeDimensionShadowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/three-dimension/shader': {
      id: '/three-dimension/shader'
      path: '/three-dimension/shader'
      fullPath: '/three-dimension/shader'
      preLoaderRoute: typeof ThreeDimensionShaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/three-dimension/particle': {
      id: '/three-dimension/particle'
      path: '/three-dimension/particle'
      fullPath: '/three-dimension/particle'
      preLoaderRoute: typeof ThreeDimensionParticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/square-apark': {
      id: '/samples/square-apark'
      path: '/samples/square-apark'
      fullPath: '/samples/square-apark'
      preLoaderRoute: typeof SamplesSquareAparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/normal-circle': {
      id: '/samples/normal-circle'
      path: '/samples/normal-circle'
      fullPath: '/samples/normal-circle'
      preLoaderRoute: typeof SamplesNormalCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/follower-circle': {
      id: '/samples/follower-circle'
      path: '/samples/follower-circle'
      fullPath: '/samples/follower-circle'
      preLoaderRoute: typeof SamplesFollowerCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/audio-circle': {
      id: '/samples/audio-circle'
      path: '/samples/audio-circle'
      fullPath: '/samples/audio-circle'
      preLoaderRoute: typeof SamplesAudioCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/5star-particle': {
      id: '/samples/5star-particle'
      path: '/samples/5star-particle'
      fullPath: '/samples/5star-particle'
      preLoaderRoute: typeof Samples5starParticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noise/fractal': {
      id: '/noise/fractal'
      path: '/noise/fractal'
      fullPath: '/noise/fractal'
      preLoaderRoute: typeof NoiseFractalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noise/fbm': {
      id: '/noise/fbm'
      path: '/noise/fbm'
      fullPath: '/noise/fbm'
      preLoaderRoute: typeof NoiseFbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noise/cellular': {
      id: '/noise/cellular'
      path: '/noise/cellular'
      fullPath: '/noise/cellular'
      preLoaderRoute: typeof NoiseCellularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection/pose': {
      id: '/detection/pose'
      path: '/detection/pose'
      fullPath: '/detection/pose'
      preLoaderRoute: typeof DetectionPoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection/hand-pose': {
      id: '/detection/hand-pose'
      path: '/detection/hand-pose'
      fullPath: '/detection/hand-pose'
      preLoaderRoute: typeof DetectionHandPoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection/fluid': {
      id: '/detection/fluid'
      path: '/detection/fluid'
      fullPath: '/detection/fluid'
      preLoaderRoute: typeof DetectionFluidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection/face-landmark': {
      id: '/detection/face-landmark'
      path: '/detection/face-landmark'
      fullPath: '/detection/face-landmark'
      preLoaderRoute: typeof DetectionFaceLandmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection/detector': {
      id: '/detection/detector'
      path: '/detection/detector'
      fullPath: '/detection/detector'
      preLoaderRoute: typeof DetectionDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/speech': {
      id: '/audio/speech'
      path: '/audio/speech'
      fullPath: '/audio/speech'
      preLoaderRoute: typeof AudioSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/mic': {
      id: '/audio/mic'
      path: '/audio/mic'
      fullPath: '/audio/mic'
      preLoaderRoute: typeof AudioMicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggregate-bill/summary': {
      id: '/aggregate-bill/summary'
      path: '/aggregate-bill/summary'
      fullPath: '/aggregate-bill/summary'
      preLoaderRoute: typeof AggregateBillSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TradeRouteChildren {
  TradeTokenRoute: typeof TradeTokenRoute
  TradeIndexRoute: typeof TradeIndexRoute
}

const TradeRouteChildren: TradeRouteChildren = {
  TradeTokenRoute: TradeTokenRoute,
  TradeIndexRoute: TradeIndexRoute,
}

const TradeRouteWithChildren = TradeRoute._addFileChildren(TradeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeltTheBorderRoute: MeltTheBorderRoute,
  PlaygroundRoute: PlaygroundRoute,
  ShaderRoute: ShaderRoute,
  StableFluidsRoute: StableFluidsRoute,
  TradeRoute: TradeRouteWithChildren,
  AggregateBillSummaryRoute: AggregateBillSummaryRoute,
  AudioMicRoute: AudioMicRoute,
  AudioSpeechRoute: AudioSpeechRoute,
  DetectionDetectorRoute: DetectionDetectorRoute,
  DetectionFaceLandmarkRoute: DetectionFaceLandmarkRoute,
  DetectionFluidRoute: DetectionFluidRoute,
  DetectionHandPoseRoute: DetectionHandPoseRoute,
  DetectionPoseRoute: DetectionPoseRoute,
  NoiseCellularRoute: NoiseCellularRoute,
  NoiseFbmRoute: NoiseFbmRoute,
  NoiseFractalRoute: NoiseFractalRoute,
  Samples5starParticleRoute: Samples5starParticleRoute,
  SamplesAudioCircleRoute: SamplesAudioCircleRoute,
  SamplesFollowerCircleRoute: SamplesFollowerCircleRoute,
  SamplesNormalCircleRoute: SamplesNormalCircleRoute,
  SamplesSquareAparkRoute: SamplesSquareAparkRoute,
  ThreeDimensionParticleRoute: ThreeDimensionParticleRoute,
  ThreeDimensionShaderRoute: ThreeDimensionShaderRoute,
  ThreeDimensionShadowsRoute: ThreeDimensionShadowsRoute,
  AggregateBillIndexRoute: AggregateBillIndexRoute,
  AudioIndexRoute: AudioIndexRoute,
  NoiseIndexRoute: NoiseIndexRoute,
  ThreeDimensionIndexRoute: ThreeDimensionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
