/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThreeDimensionIndexImport } from './routes/three-dimension/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreeDimensionIndexRoute = ThreeDimensionIndexImport.update({
  id: '/three-dimension/',
  path: '/three-dimension/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/three-dimension/': {
      id: '/three-dimension/'
      path: '/three-dimension'
      fullPath: '/three-dimension'
      preLoaderRoute: typeof ThreeDimensionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/three-dimension': typeof ThreeDimensionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/three-dimension': typeof ThreeDimensionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/three-dimension/': typeof ThreeDimensionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/three-dimension'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/three-dimension'
  id: '__root__' | '/' | '/three-dimension/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreeDimensionIndexRoute: typeof ThreeDimensionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreeDimensionIndexRoute: ThreeDimensionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/three-dimension/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/three-dimension/": {
      "filePath": "three-dimension/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
